### ISSUE TITLE
Vue2 版本的 v-contextmenu 存在内存泄漏问题

### ISSUE THREAD

**Issue by wfk007** [CyberNika/v-contextmenu#140]
## 期望结果

组件销毁后，window 上挂的 $$VContextmenu 可以销毁

## 实际结果

组件销毁后，window 上挂的 $$VContextmenu 没有销毁
<img width="504" alt="image" src="https://github.com/CyberNika/v-contextmenu/assets/22289445/289011eb-b6fa-4526-b31d-6a290c4657dc">

## 复现步骤

1. Git clone https://github.com/wfk007/v-contextmenu-memory-leak
2. npm install
3. npm run serve
4. 点击切换按钮

## 环境说明

- 组件版本：2.9.0
- `Vue` 版本：2.7.15
- 操作系统及版本：macOS Catalina 10.15.7
- 浏览器及版本：120.0.6099.71

**Comment by CyberNika** [comment]
有解决这个问题的思路吗？欢迎提 PR。

**Comment by wfk007** [comment]
> 有解决这个问题的思路吗？欢迎提 PR。

@CyberNika 我提了个 PR https://github.com/CyberNika/v-contextmenu/pull/142

**Comment by CyberNika** [comment]
`v2.9.1` 已发布
