### ISSUE TITLE
ie报错

### ISSUE THREAD

**Issue by lerit** [CyberNika/v-contextmenu#48]
IE下,无法显示,官方的demo也看不了
## 期望结果

支持ie
## 实际结果

不支持ie
## 复现步骤

1.ie edge 打开官方demo
2.看不到界面
3.根据调试控制台显示,应该是不支持find方法
![ie11-error](https://user-images.githubusercontent.com/4743467/46183669-7b41de80-c304-11e8-8012-3ea7f9174038.png)

## 环境说明

- 组件版本：
- `Vue` 版本：2.5.16
- 操作系统及版本：win10
- 浏览器及版本：ie edge

**Comment by welkinwong** [comment]
IE11报错……
