### ISSUE TITLE
菜单里的右键

### ISSUE THREAD

**Issue by ray-zyh** [CyberNika/v-contextmenu#49]
## 期望结果

右键弹出的自定义菜单中, 在菜单右键后不要弹出系统菜单 
## 实际结果

自定义的右键 菜单 再右击会弹出浏览器的默认菜单 ,加入 @contextmenu.prevent="" 也不起作用
## 环境说明

- 组件版本：
- `Vue` 版本：
- 操作系统及版本：
- 浏览器及版本：

**Comment by CyberNika** [comment]
https://github.com/CyberNika/v-contextmenu/releases/tag/v3.2.0
