### ISSUE TITLE
菜单内容过多过长时顶部内容溢出浏览区域 

### ISSUE THREAD

**Issue by josephvong** [CyberNika/v-contextmenu#51]
内容过多时，在某些情况下，菜单顶部内容会溢出浏览器顶部可视范围
## 期望结果

菜单的顶部 （top） 至少 >=0
## 实际结果

内容过多时，在某些情况下，菜单顶部内容会溢出浏览器顶部可视范围
## 环境说明

- 组件版本：
- `Vue` 版本：
- 操作系统及版本：
- 浏览器及版本：

**Comment by CyberNika** [comment]
`v3`
