### ISSUE TITLE
disabled属性与选择事件冲突

### ISSUE THREAD

**Issue by DerekMar** [CyberNika/v-contextmenu#52]
当我需要，点击contextmenu的指定项后，需要disable该项时，出现如下效果：
![image](https://user-images.githubusercontent.com/20637828/50042927-43963780-00a6-11e9-8ce6-0a4be8f20c11.png)

## 实际结果

我希望，当指定项无效时，应该去掉selected的效果
## 复现步骤
绑定 :disabled="!isDrawing"，点击该项后，将 isDrawing = !isDrawing，会出现上述结果

## 环境说明

- 组件版本：
- `Vue` 版本：
- 操作系统及版本：
- 浏览器及版本：

**Comment by dracarys26** [comment]
不改代码只能加个css了..
`css
.v-contextmenu-item--disabled.v-contextmenu-item--hover{
          color: #ccc;
          cursor: not-allowed;
          background: transparent !important;
}
`

**Comment by DerekMar** [comment]
> 不改代码只能加个css了..
> `css .v-contextmenu-item--disabled.v-contextmenu-item--hover{ color: #ccc; cursor: not-allowed; background: transparent !important; } `

我直接修改了源码，其实就是语句执行顺序换一下而已

**Comment by dracarys26** [comment]
@DerekMar 是滴,disabled直接return了, 但是不想把代码拷到项目里- -

**Comment by snokier** [comment]
@DerekMar @dracarys26 可以考虑提个 PR 😋
